### ISSUE TITLE
Search and Display Functionalities

### ISSUE THREAD

**Issue by Abdurahman-hassan** [Abdurahman-hassan/Bookstore-manager#7]
- Implement Book Search Feature
  - Develop a search function for users to find books.
- Create Display All Books Feature
  - Implement a feature to display all book records.
- Develop Advanced Book Display Options
  - Add options to display books per category, name, price, author, rate.

**Comment by Abdurahman-hassan** [comment]
we need to implement this 

- Advanced Book Display Options
Add options to display books per category, name, price, author, rate. @itsalhussein @devahmedtaleb

**Comment by itsalhussein** [comment]
@Abdurahman-hassan  Noted, working on it.

**Comment by Abdurahman-hassan** [comment]
Done
